repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3000']
      # - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
    - id: ruff
      args:
        [
          --fix,
          --exit-non-zero-on-fix,
          --show-fixes
          ]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - boto3==1.37.29
          - botocore==1.37.29
          - python-dotenv==1.1.0
          - loguru==0.7.3
          - streamlit==1.44.1
          - requests==2.32.3
          - pytest==8.3.5
          - types-requests==2.32.0.20250328
          - mypy-boto3-cognito-idp==1.37.13.post1
          - boto3-stubs>=1.37.37
        args:
          [
            --config-file=pyproject.toml,
            ]

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
        - mdformat-gfm

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false

  # -   repo: local
  #     hooks:
  #     -   id: clean-generated-files
  #         name: Clean Generated Files
  #         entry: ./clean_generated.sh
  #         language: system
  #         stages: [commit] # Or other stages like manual
