version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.3.1

jobs:
  build-deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create venv and install dependencies
          command: |
            uv sync --all-groups

      - run:
          name: Run ruff
          command: |
            uv run ruff check . --fix --exit-non-zero-on-fix

      - run:
          name: Run MyPy
          command: |
            uv run mypy

      - aws-cli/setup:
          profile_name: default

      - run:
          name: Configure Cognito App
          command: |
            uv run src/cognito_app.py

      - run:
          name: Configure Hosted Domain
          command: |
            uv run src/hosted_domain.py

      - run:
          name: Configure Google IDP
          command: |
            uv run src/google_idp.py

      - run:
          name: Configure Client Login Pages
          command: |
            uv run src/client_login_pages.py

      - run:
          name: Run tests
          command: |
            uv run pytest

workflows:
  deploy:
    jobs:
      - build-deploy
